/* eslint-disable react/no-unescaped-entities */
export default function Impressum() {
  return (
    <>
      <section className="mt-5 card bg-white rounded-3 p-4">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h1 className="mb-3">IMPRESSUM</h1>
            </div>
          <div>
              <p>
                <strong>Web Waiters is a brand of</strong>
              </p>

              <p>
                Web Waiters GmbH
                <br />
                Straßer 77
                <br />
                1044 Berlin
                <br />
                <br />
                Managing Director: [Name]
                <br />
                VAT ID: [VAT ID]
                <br />
                Commercial register: [Commercial register]
                <br />
                DUNS Number: [DUNS Number]
                <br />
                <br />
                Contact: mail@1234567.com
                <br />
                Phone: +91 90904500112
                <br />
                <br />
                Terms and conditions
                <br />
                By accessing the content of this website, you agree to be bound by the terms and conditions set out herein and you accept our privacy policy available on this website. This statement covers this website, its sub-sites, and all other websites. If you object to any of the terms and conditions set out in this agreement, you should not use any of the products or services on this website and leave immediately. You agree that you shall not use this website for illegal purposes and will respect all applicable laws and regulations. You agree not to use this website in a way that may impair the performance, corrupt the content, or otherwise reduce the overall functionality of this website. You also agree not to compromise the security of this website or attempt to gain access to secured areas or sensitive information. You agree to be fully responsible for any claim, expense, liability, losses, costs, including legal fees incurred by us arising from any infringement of the terms and conditions set out in this agreement.
                <br />
                <br />
                Disclaimers
                <br />
                Web Waiters GmbH is not responsible for the content on the Internet or worldwide web pages that are contained outside the website www.web-waiters.com. We may provide links to resources that are beyond our control. We make no representations as to the quality, suitability, functionality, or legality of any sites to which we may provide links, and you hereby waive any claim you might have against Web Waiters GmbH with respect to such sites.
                <br />
                <br />
                Copyright Information
                <br />
                This website and the associated database contain materials created, developed, designed, or commissioned by Web Waiters GmbH and are protected by European and international copyright and trademark laws. No material (including but not limited to names, text, logos, images, audio, and/or video) and no software and mobile applications (including but not limited to any images or files incorporated in or generated by the software application) may be copied, distributed, posted, reproduced, republished, transmitted, or uploaded in any way. In connection with such use, you may not modify or obscure any copyright or other proprietary notice. Modification or other use of these materials without Web Waiters's prior written consent is a violation of Web Waiters's proprietary rights.
                <br />
                <br />
                Governing law and jurisdiction
                <br />
                This Agreement will be governed by the laws of Germany, and any user of this website hereby agrees to be bound exclusively by the jurisdiction of German courts without reference to rules governing choice of laws.
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
